In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
import seaborn as sns
from category_encoders import TargetEncoder
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error

In [ ]:
df=pd.read_csv('winequality-red.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
df.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [ ]:
x=df.drop(columns=['quality'])
y=df['quality']

In [ ]:
df.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [ ]:
x

      fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0               7.4             0.700         0.00  ...  3.51       0.56      9.4
1               7.8             0.880         0.00  ...  3.20       0.68      9.8
2               7.8             0.760         0.04  ...  3.26       0.65      9.8
3              11.2             0.280         0.56  ...  3.16       0.58      9.8
4               7.4             0.700         0.00  ...  3.51       0.56      9.4
...             ...               ...          ...  ...   ...        ...      ...
1594            6.2             0.600         0.08  ...  3.45       0.58     10.5
1595            5.9             0.550         0.10  ...  3.52       0.76     11.2
1596            6.3             0.510         0.13  ...  3.42       0.75     11.0
1597            5.9             0.645         0.12  ...  3.57       0.71     10.2
1598            6.0             0.310         0.47  ...  3.39       0.66     11.0

[1599 rows x 11 columns]

In [ ]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.8,random_state=42)

In [ ]:
cat_cols = x.select_dtypes(include='object').columns
df[cat_cols].nunique()

Series([], dtype: float64)

In [ ]:
num_cols= x.select_dtypes(include='number').columns
df[num_cols].nunique()

fixed acidity            96
volatile acidity        143
citric acid              80
residual sugar           91
chlorides               153
free sulfur dioxide      60
total sulfur dioxide    144
density                 436
pH                       89
sulphates                96
alcohol                  65
dtype: int64

In [ ]:
main_pipline = Pipeline(
    steps=[
        ('model', DecisionTreeClassifier(
            random_state=42,
            criterion='entropy'
            ))
    ]
)

main_pipline.fit(xtrain,ytrain)

Pipeline(steps=[('model',
                 DecisionTreeClassifier(criterion='entropy', random_state=42))])

## Using model Random Forest Regressor

In [ ]:
regressor = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
)
regressor.fit(xtrain,ytrain)

RandomForestRegressor(random_state=42)

In [ ]:
# Predict on train data
ytrain_pred = regressor.predict(xtrain)

In [ ]:
ytrain_pred

array([5.33, 4.95, 5.22, 5.94, 6.89, 6.62, 5.9 , 5.13, 6.13, 5.97, 5.14,
       6.27, 5.93, 5.99, 4.99, 5.17, 6.21, 5.01, 3.82, 6.02, 6.06, 5.96,
       6.07, 5.62, 6.01, 5.97, 5.05, 4.98, 6.08, 5.42, 6.83, 5.05, 5.95,
       6.94, 5.1 , 5.17, 6.73, 6.07, 5.98, 5.84, 5.05, 6.69, 5.94, 6.02,
       5.03, 4.44, 5.98, 4.95, 5.09, 5.39, 6.  , 5.  , 6.39, 5.76, 6.5 ,
       5.91, 5.79, 5.04, 5.89, 6.89, 5.19, 5.15, 5.92, 6.15, 5.22, 5.87,
       5.23, 6.09, 5.79, 6.02, 5.02, 5.11, 5.  , 5.83, 5.48, 6.71, 5.17,
       5.99, 5.06, 6.02, 6.03, 5.03, 4.2 , 4.81, 5.19, 5.08, 6.51, 6.02,
       5.95, 5.19, 5.06, 5.11, 6.01, 5.04, 6.89, 5.89, 5.85, 5.02, 4.88,
       5.14, 5.17, 5.03, 5.11, 5.95, 5.04, 6.02, 5.09, 6.11, 6.06, 5.01,
       5.06, 5.09, 5.07, 4.96, 5.83, 6.84, 5.3 , 5.97, 5.87, 6.04, 6.05,
       5.03, 5.13, 6.08, 5.63, 5.98, 5.02, 5.87, 6.55, 5.83, 5.06, 5.9 ,
       6.84, 5.07, 5.84, 5.23, 5.  , 6.83, 6.02, 5.08, 5.37, 6.17, 5.15,
       6.73, 4.9 , 5.22, 6.45, 4.91, 5.91, 5.81, 5.  , 5.85, 5.87, 5.07,
       5.01, 6.88, 5.04, 5.68, 5.86, 6.88, 5.35, 6.18, 6.  , 6.01, 5.95,
       6.14, 5.32, 5.02, 5.1 , 6.96, 6.94, 5.07, 6.08, 5.95, 6.01, 5.06,
       4.26, 5.13, 5.9 , 5.02, 5.72, 5.84, 4.97, 5.09, 4.76, 5.72, 5.94,
       6.81, 5.04, 6.88, 6.95, 5.09, 6.63, 5.35, 4.91, 5.44, 6.02, 6.66,
       6.42, 6.62, 6.04, 5.49, 5.08, 6.83, 6.94, 4.33, 5.1 , 5.92, 5.93,
       4.85, 5.06, 6.1 , 5.88, 6.96, 6.02, 5.04, 4.98, 5.12, 5.02, 6.08,
       5.63, 5.36, 5.02, 4.98, 6.9 , 5.63, 5.28, 7.23, 6.02, 5.35, 5.96,
       5.8 , 5.11, 4.42, 5.75, 5.91, 5.73, 5.08, 5.96, 5.18, 5.25, 6.01,
       5.76, 5.95, 6.16, 6.94, 5.17, 4.81, 5.8 , 6.66, 3.71, 6.09, 6.06,
       5.58, 4.49, 5.85, 6.26, 4.5 , 5.89, 6.01, 5.01, 6.01, 4.17, 5.59,
       6.1 , 5.08, 6.92, 5.75, 5.28, 6.03, 5.95, 5.95, 5.94, 6.16, 5.03,
       5.97, 5.1 , 5.91, 5.03, 5.06, 5.95, 6.05, 5.05, 5.63, 5.74, 6.06,
       5.02, 5.26, 5.23, 4.95, 3.88, 5.28, 5.87, 5.34, 6.01, 5.73, 6.93,
       5.07, 5.95, 5.79, 5.07, 5.68, 5.07, 5.19, 6.  , 5.09, 5.12, 4.4 ,
       6.18, 4.4 , 6.01, 5.92, 6.29, 5.17, 5.85, 5.97, 5.01, 6.73, 6.07])

In [ ]:
# Predict on test data
ytest_pred = regressor.predict(xtest)

In [ ]:
ytest_pred

array([5.2 , 5.04, 5.34, ..., 5.62, 5.27, 6.05], shape=(1280,))

In [ ]:
# Test data
print(r2_score(ytrain,ytrain_pred))

0.9247089731130548

In [ ]:
print(root_mean_squared_error(ytrain,ytrain_pred))

0.21372938680419934

In [ ]:
print(mean_absolute_error(ytrain,ytrain_pred))

0.15115987460815042

In [ ]:
print(mean_squared_error(ytrain,ytrain_pred))

0.04568025078369906

In [ ]:
# Train Data
print(r2_score(ytest,ytest_pred))

0.3166237089532522

In [ ]:
print(root_mean_squared_error(ytest,ytest_pred))

0.6731023092740063

In [ ]:
print(mean_squared_error(ytest,ytest_pred))

0.45306671875

In [ ]:
print(mean_absolute_error(ytest,ytest_pred))

0.507671875