In [16]:
import pandas as pd
from sklearn.ensemble import IsolationForest

In [17]:
df = pd.read_csv('creditcard.csv')

In [18]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [19]:
df.shape

(284807, 31)

In [20]:
print(284807*0.05)

14240.35

In [ ]:
model = IsolationForest(
    n_estimators=100,
    max_samples=0.8,
    max_features=1.0,
    bootstrap=True,
    n_jobs=1,
    verbose=5,
    random_state=42,
    contamination=0.05 #5% #auto
    )
result = model.fit_predict(df)
anamolies = df[result==-1]
normal = df[result==1]

Building estimator 1 of 100 for this parallel run (total 100)...
Building estimator 2 of 100 for this parallel run (total 100)...
Building estimator 3 of 100 for this parallel run (total 100)...
Building estimator 4 of 100 for this parallel run (total 100)...
Building estimator 5 of 100 for this parallel run (total 100)...
Building estimator 6 of 100 for this parallel run (total 100)...
Building estimator 7 of 100 for this parallel run (total 100)...
Building estimator 8 of 100 for this parallel run (total 100)...
Building estimator 9 of 100 for this parallel run (total 100)...
Building estimator 10 of 100 for this parallel run (total 100)...
Building estimator 11 of 100 for this parallel run (total 100)...
Building estimator 12 of 100 for this parallel run (total 100)...
Building estimator 13 of 100 for this parallel run (total 100)...
Building estimator 14 of 100 for this parallel run (total 100)...
Building estimator 15 of 100 for this parallel run (total 100)...
Building estimator 16 of 100 for this parallel run (total 100)...
Building estimator 17 of 100 for this parallel run (total 100)...
Building estimator 18 of 100 for this parallel run (total 100)...
Building estimator 19 of 100 for this parallel run (total 100)...
Building estimator 20 of 100 for this parallel run (total 100)...
Building estimator 21 of 100 for this parallel run (total 100)...
Building estimator 22 of 100 for this parallel run (total 100)...
Building estimator 23 of 100 for this parallel run (total 100)...
Building estimator 24 of 100 for this parallel run (total 100)...
Building estimator 25 of 100 for this parallel run (total 100)...
Building estimator 26 of 100 for this parallel run (total 100)...
Building estimator 27 of 100 for this parallel run (total 100)...
Building estimator 28 of 100 for this parallel run (total 100)...
Building estimator 29 of 100 for this parallel run (total 100)...
Building estimator 30 of 100 for this parallel run (total 100)...
Building estimator 31 of 100 for this parallel run (total 100)...
Building estimator 32 of 100 for this parallel run (total 100)...
Building estimator 33 of 100 for this parallel run (total 100)...
Building estimator 34 of 100 for this parallel run (total 100)...
Building estimator 35 of 100 for this parallel run (total 100)...
Building estimator 36 of 100 for this parallel run (total 100)...
Building estimator 37 of 100 for this parallel run (total 100)...
Building estimator 38 of 100 for this parallel run (total 100)...
Building estimator 39 of 100 for this parallel run (total 100)...
Building estimator 40 of 100 for this parallel run (total 100)...
Building estimator 41 of 100 for this parallel run (total 100)...
Building estimator 42 of 100 for this parallel run (total 100)...
Building estimator 43 of 100 for this parallel run (total 100)...
Building estimator 44 of 100 for this parallel run (total 100)...
Building estimator 45 of 100 for this parallel run (total 100)...
Building estimator 46 of 100 for this parallel run (total 100)...
Building estimator 47 of 100 for this parallel run (total 100)...
Building estimator 48 of 100 for this parallel run (total 100)...
Building estimator 49 of 100 for this parallel run (total 100)...
Building estimator 50 of 100 for this parallel run (total 100)...
Building estimator 51 of 100 for this parallel run (total 100)...
Building estimator 52 of 100 for this parallel run (total 100)...
Building estimator 53 of 100 for this parallel run (total 100)...
Building estimator 54 of 100 for this parallel run (total 100)...
Building estimator 55 of 100 for this parallel run (total 100)...
Building estimator 56 of 100 for this parallel run (total 100)...
Building estimator 57 of 100 for this parallel run (total 100)...
Building estimator 58 of 100 for this parallel run (total 100)...
Building estimator 59 of 100 for this parallel run (total 100)...
Building estimator 60 of 100 for this parallel run (total 100)...
Building estimator 61 of 100 for this parallel run (total 100)...
Building estimator 62 of 100 for this parallel run (total 100)...
Building estimator 63 of 100 for this parallel run (total 100)...
Building estimator 64 of 100 for this parallel run (total 100)...
Building estimator 65 of 100 for this parallel run (total 100)...
Building estimator 66 of 100 for this parallel run (total 100)...
Building estimator 67 of 100 for this parallel run (total 100)...
Building estimator 68 of 100 for this parallel run (total 100)...
Building estimator 69 of 100 for this parallel run (total 100)...
Building estimator 70 of 100 for this parallel run (total 100)...
Building estimator 71 of 100 for this parallel run (total 100)...
Building estimator 72 of 100 for this parallel run (total 100)...
Building estimator 73 of 100 for this parallel run (total 100)...
Building estimator 74 of 100 for this parallel run (total 100)...
Building estimator 75 of 100 for this parallel run (total 100)...
Building estimator 76 of 100 for this parallel run (total 100)...
Building estimator 77 of 100 for this parallel run (total 100)...
Building estimator 78 of 100 for this parallel run (total 100)...
Building estimator 79 of 100 for this parallel run (total 100)...
Building estimator 80 of 100 for this parallel run (total 100)...
Building estimator 81 of 100 for this parallel run (total 100)...
Building estimator 82 of 100 for this parallel run (total 100)...
Building estimator 83 of 100 for this parallel run (total 100)...
Building estimator 84 of 100 for this parallel run (total 100)...
Building estimator 85 of 100 for this parallel run (total 100)...
Building estimator 86 of 100 for this parallel run (total 100)...
Building estimator 87 of 100 for this parallel run (total 100)...
Building estimator 88 of 100 for this parallel run (total 100)...
Building estimator 89 of 100 for this parallel run (total 100)...
Building estimator 90 of 100 for this parallel run (total 100)...
Building estimator 91 of 100 for this parallel run (total 100)...
Building estimator 92 of 100 for this parallel run (total 100)...
Building estimator 93 of 100 for this parallel run (total 100)...
Building estimator 94 of 100 for this parallel run (total 100)...
Building estimator 95 of 100 for this parallel run (total 100)...
Building estimator 96 of 100 for this parallel run (total 100)...
Building estimator 97 of 100 for this parallel run (total 100)...
Building estimator 98 of 100 for this parallel run (total 100)...
Building estimator 99 of 100 for this parallel run (total 100)...
Building estimator 100 of 100 for this parallel run (total 100)...

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.9s finished
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.0s finished
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.1s finished

In [22]:
set(result)

{np.int64(-1), np.int64(1)}

In [23]:
''' 
model = IsolationForest(
    n_estimators=100,
    max_samples=0.8,
    max_features=1.0,
    bootstrap=True,
    n_jobs=1,
    verbose=5
)
'''

' \nmodel = IsolationForest(\n    n_estimators=100,\n    max_samples=0.8,\n    max_features=1.0,\n    bootstrap=True,\n    n_jobs=1,\n    verbose=5\n)\n'

In [25]:
df[result==-1]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
48,35.0,1.386397,-0.794209,0.778224,-0.864708,-1.064132,0.351296,-1.191455,0.052686,-0.304404,...,-0.228727,-0.123522,-0.131025,-0.929668,0.181379,1.194928,0.000531,0.019911,30.90,0
51,36.0,-1.004929,-0.985978,-0.038039,3.710061,-6.631951,5.122103,4.371691,-2.006868,-0.278736,...,1.393406,-0.381671,0.969719,0.019445,0.570923,0.333278,0.857373,-0.075538,1402.95,0
69,46.0,-1.923213,-0.870482,2.320170,1.988776,0.417091,-0.380014,0.472139,-0.557333,-0.649079,...,-0.686488,-0.779268,1.086055,0.518863,-0.363712,3.065576,-0.589022,-0.396110,35.00,0
82,52.0,-3.005237,2.600138,1.483691,-2.418473,0.306326,-0.824575,2.065426,-1.829347,4.009259,...,-0.852309,-0.181268,-0.163747,0.515821,0.136318,0.460054,-0.251259,-1.105751,1.46,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284770,172759.0,-0.822731,1.270140,-0.138566,0.479620,1.242101,0.795218,0.454284,0.556038,-1.550610,...,0.138766,0.450908,-0.192146,-0.196218,-0.261664,2.372675,-0.042743,0.109613,0.00,0
284782,172767.0,-0.268061,2.540315,-1.400915,4.846661,0.639105,0.186479,-0.045911,0.936448,-2.419986,...,-0.263889,-0.857904,0.235172,-0.681794,-0.668894,0.044657,-0.066751,-0.072447,12.82,0
284795,172778.0,-12.516732,10.187818,-8.476671,-2.510473,-4.586669,-1.394465,-3.632516,5.498583,4.893089,...,-0.944759,-1.565026,0.890675,-1.253276,1.786717,0.320763,2.090712,1.232864,9.87,0
284798,172782.0,0.219529,0.881246,-0.635891,0.960928,-0.152971,-1.014307,0.427126,0.121340,-0.285670,...,0.099936,0.337120,0.251791,0.057688,-1.508368,0.144023,0.181205,0.215243,24.05,0
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0

In [27]:
print(result)
result = result[:50]

[ 1  1 -1 ...  1  1  1]

In [28]:
df[result==1]

ValueError: Item wrong length 50 instead of 284807.